#ifndef INC_MESSAGEPASSING_ERRORS_H_
#define INC_MESSAGEPASSING_ERRORS_H_

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef enum : uint32_t
{
    ERROR_BPM_PWM_START_FAILURE = 0,
    ERROR_BPM_PWM_STOP_FAILURE,
    ERROR_FORCE_SENSOR_ADC_START_FAILURE = 100,
    ERROR_FORCE_SENSOR_ADS1115_INIT_FAILURE,
    ERROR_LUMEX_LCD_TIMER_START_FAILURE = 200,
    FIRST_WARNING_NUMBER = 10000,
    WARNING_FORCE_SENSOR_ADS1115_TRIGGER_CONVERSION_FAILURE = 10200,
    WARNING_FORCE_SENSOR_ADS1115_GET_CONVERSION_FAILURE,
    WARNING_PID_CONTROLLER_MESSAGE_QUEUE_FULL = 10300,

} task_errors;



#ifdef __cplusplus
}
#endif

#endif // INC_MESSAGEPASSING_ERRORS_H_