#ifndef INC_CONFIG_CONFIG_H_
#define INC_CONFIG_CONFIG_H_

#include "../../../../stm32_dyno_firmware_sensor_board/Drivers/ADS1115/ADS1115_defines.h"

// Voltage Reference (should be 3V3)
#define VREF 3.3f

// Mechanical Power Calculation Constants
#define DISTANCE_FROM_FORCE_SENSOR_TO_CENTER_OF_SHAFT_M 1.0f
#define MOMENT_OF_INERTIA_KG_M2 1.0f

// Optical Encoder Config
#define NUM_APERTURES 64

// Force Sensor Config
#define MAX_FORCE_LBF 25.0f

// Main PID controller parameters
#define K_P 1.0f
#define K_I 1.0f
#define K_D 1.0f
#define PID_MAX_OUTPUT 100.0f
#define THROTTLE_GAIN 1.0f
#define BRAKE_GAIN 1.0f
#define HORIZONTAL_BIAS 0.0f
#define VERTICAL_BIAS 0.0f

// User Input Config (like buttons)
#define USER_INPUT_CIRCULAR_BUFFER_SIZE 100

// Session Controller Config
#define SESSIONCONTROLLER_TASK_OSDELAY 5

// BPM Config
#define MIN_DUTY_CYCLE_PERCENT 0.0f
#define MAX_DUTY_CYCLE_PERCENT 0.95f
#define BPM_CIRCULAR_BUFFER_SIZE 100
#define BPM_TASK_OSDELAY 3

// SENSOR BOARD CONTROLLER Config
#define SENSOR_BOARD_CONTROLLER_TASK_OSDELAY 5
#define ADS1115_FORCESENSOR_VOLTAGE 5.1f
#define FORCESENSOR_CIRCULAR_BUFFER_SIZE 100
#define OPTICAL_ENCODER_CIRCULAR_BUFFER_SIZE 100

#define OPTICAL_SENSOR_ACK_MAX_RETRIES 5
#define FORCE_SENSOR_ADC_ACK_MAX_RETRIES 5
#define ADS1115_ACK_MAX_RETRIES 5

// ADS1115 I2C Config
#define ADS1115_DEFAULT_MULTIPLEXER_SETTING ADS1115_MUX_P0_NG
#define ADS1115_DEFAULT_COMPARATOR_MODE ADS1115_COMP_MODE_HYSTERESIS
#define ADS1115_DEFAULT_COMPARATOR_POLARITY ADS1115_COMP_POL_ACTIVE_LOW
#define ADS1115_DEFAULT_COMPARATOR_LATCH_ENABLED ADS1115_COMP_LAT_NON_LATCHING
#define ADS1115_DEFAULT_COMPARATOR_QUEUE_MODE ADS1115_COMP_QUE_DISABLE
#define ADS1115_DEFAULT_MODE ADS1115_MODE_SINGLESHOT
#define ADS1115_SAMPLE_SPEED ADS1115_RATE_475
#define ADS1115_DEFAULT_GAIN ADS1115_PGA_6P144

// PID config
#define PID_INITIAL_STATUS false
#define PID_TASK_OSDELAY 10

// USB config
#define USB_TX_BUFFER_SIZE 512 // Buffer that is being sent to USB peripheral
#define USB_TASK_OSDELAY 5

// LCD config
#define LCD_TASK_OSDELAY 20
#define SESSION_CONTROLLER_TO_LUMEX_LCD_MSG_STRING_SIZE 16 + 1

// LED config
#define LED_TASK_OSDELAY 500

// Error and Warning settings
#define TASK_ERROR_CIRCULAR_BUFFER_SIZE 50
#define TASK_WARNING_RETRY_OSDELAY 100

// Task Monitor config
#define TASK_MONITOR_TASK_OSDELAY 1000





#endif /* INC_CONFIG_CONFIG_H_ */
