#include "MessagePassing/circular_buffers.h"

uint32_t optical_encoder_circular_buffer_index_writer = 0;
uint32_t forcesensor_circular_buffer_index_writer = 0;
uint32_t bpm_circular_buffer_index_writer = 0;

optical_encoder_output_data optical_encoder_circular_buffer[OPTICAL_ENCODER_CIRCULAR_BUFFER_SIZE];
forcesensor_output_data forcesensor_circular_buffer[FORCESENSOR_CIRCULAR_BUFFER_SIZE];
bpm_output_data bpm_circular_buffer[BPM_CIRCULAR_BUFFER_SIZE];
